version: 2.1
jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      # If changing build tools be sure to update GeneratorSetup.md in docs
      - run: gradle fatJar :output:test :profile:test :generator:test :common:test :orchestrator:test
      - run:
          name: test
          command: find . -type f -regex ".*/build/.*";
      - run:
          name: test2
          command: pwd;
      - run:
          name: Save jar
          command: |
            mkdir -p ~/artifacts/
            cp ./generator/build/libs/generator.jar ~/artifacts/ \
          when: always
      - store_artifacts:
          path: ~/generator.jar
      # This is where you need to aff the line to output the jar to another github repo

  release:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      # If changing build tools be sure to update GeneratorSetup.md in docs
      - run: gradle :output:release :profile:release :generator:release :orchestrator:release
      - store-artifacts:
          path: schemas/build/libs
      - store-artifacts:
          path: generator/build/libs

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
# TODO: Ensure gradle migration is smooth before introducing release job
#  release:
#    jobs:
#      - release:
#          filters:
#            branches:
#              only: master
